spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      username: testuser
      password: testpass
    url: jdbc:postgresql://localhost:5432/study

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true